apiVersion: v1
kind: Pod
metadata:
  name: vault-agent-example
  namespace: default
spec:
  serviceAccountName: vault-auth

  volumes:
  - configMap:
      items:
      - key: vault-agent-config.hcl
        path: vault-agent-config.hcl
      - key: vault-agent-rendered.hcl
        path: vault-agent-rendered.hcl
      name: example-vault-agent-config
    name: config
  - emptyDir:
      medium: Memory
    name: shared-data

  initContainers:
  - args:
    - agent
    - -config=/etc/vault/vault-agent-config.hcl
    - -log-level=debug
    env:
    - name: VAULT_ADDR
      value: http://vault:8200
    image: hashicorp/vault:latest
    name: vault-agent
    volumeMounts:
    - mountPath: /etc/vault
      name: config
    - mountPath: /etc/secrets
      name: shared-data

  containers:
  - image: nginx:latest
    name: nginx-container
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-data
#    resources:
#      requests:
#        memory: 256Mi
#        cpu: "0.2"
#      limits:
#        memory: 512Mi
#        cpu: "0.4"
  - image: hashicorp/vault:latest
    name: vault-agent-remdered
    args:
    - agent
    - -config=/etc/vault/vault-agent-rendered.hcl
    - -log-level=debug
    env:
    - name: VAULT_ADDR
      value: http://vault:8200
    volumeMounts:
    - mountPath: /etc/vault
      name: config
    - mountPath: /etc/secrets
      name: shared-data
