--- 
- name: Consul Server | Install Packages
  ansible.builtin.yum:
    disable_gpg_check: yes
    name: 
      - unzip
      - bind-utils
    state: latest
    update_cache: yes

- name: Consul Server | Add user
  ansible.builtin.user:
    name: "consul"
    shell: /bin/false
    system: false 
    create_home: false

- name: Consul Server | Copy consul binaries
  ansible.builtin.copy:
    src: "consul/{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
  - src: consul_1.17.0_linux_amd64.zip
    dest: /tmp/consul_1.17.0_linux_amd64.zip
  - src: consul-template_0.35.0_linux_amd64.zip
    dest: /tmp/consul-template_0.35.0_linux_amd64.zip

- name: Consul Server | Unarchive consul binaries
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: /usr/local/sbin
    remote_src: true
  loop:
  - "/tmp/consul_1.17.0_linux_amd64.zip"
  - "/tmp/consul-template_0.35.0_linux_amd64.zip"

- name: Consul Server | Make directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
  loop:
  - /etc/consul.d/
  - /var/lib/consul

- name: Consul Server | Configure
  ansible.builtin.template:
    src: consul/consul-server.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
  notify: reload consul

- name: Consul Server | Copy systemd unit
  ansible.builtin.template:
    src: consul/consul.service
    dest: /etc/systemd/system/consul.service

- name: Consul Server | Start consul service
  ansible.builtin.systemd:
    name: consul
    state: started
    daemon_reload: true