---
# systemctl enable nftables --now
- name: Start NFTables Service
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: yes

# systemctl enable nginx --now
- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes