--- 
# systemctl restart chrony 
- name: Restart Chrony Debian
  ansible.builtin.service:
    name: Chrony  
    state: restarted
    deamon_reload: yes


# systemctl restart chronyd 
- name: Restart Chronyd RedHat
  ansible.builtin.service: 
    name: chronyd
    state: restarted 
    deamon_reload: yes 