#cloud-config
runcmd:
  - rpm --import https://repo.saltproject.io/salt/py3/redhat/9/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub
  - curl -fsSL https://repo.saltproject.io/salt/py3/redhat/9/x86_64/minor/3006.4.repo | tee /etc/yum.repos.d/salt.repo
  - dnf install salt-minion -y
  - systemctl enable --now salt-minion