---

# tsaksfile for php 
- name: debians OS
  
  block:
    - name: Install PHP-FPM Debian 
      ansible.builtin.apt:
        name: 
          - "php{{ php_version }}-fpm"
          - "php{{ php_version }}-mysql"
          - "php{{ php_version }}-bcmath"
          - "php{{ php_version }}-ctype"
          - "php{{ php_version }}-json"
          - "php{{ php_version }}-mbstring"
          - "php{{ php_version }}-pdo"
          - "php{{ php_version }}-tokenizer"
          - "php{{ php_version }}-xml"
          - "php{{ php_version }}-curl"
        state: latest
        update_cache: yes 


  when: ansible_os_family == 'Debian'


- name: RedHat OS
  block:

    - name: Install EPEL Repo
      ansible.builtin.yum:
        disable_gpg_check: yes
        name: 
          - epel-release
        state: latest
        
- name: Install PHP-FPM Redhat
  ansible.builtin.yum:
    disable_gpg_check: yes
    name: 
      - "php-fpm"
      - "php-mysqlnd"
      - "php-bcmath"
      - "php-ctype"
      - "php-json"
      - "php-mbstring"
      - "php-pdo"
      - "php-tokenizer"
      - "php-xml"
      - "php-curl" 
    state: present



  when: ansible_os_family == 'RedHat'


# mkdir -p /var/www/html/
- name: Create html directory
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: '0755'
  when: "ansible_hostname in 'backend-01'"
   
# cp html/index.php.j2 /var/www/html/index.php
- name: Tempalte index.php.j2 /var/www/html/index.php
  ansible.builtin.template:
    src: "html/{{ item }}.j2"
    dest: "/var/www/html/{{ item }}"
  loop:
    - index.php
    - add.php
    - update.php
    - delete.php
    - phpinfo.php
  when: "ansible_hostname in 'backend-01'"


# systemctl restart php-fpm.service
- name: Start php-fpm service Debian 
  ansible.builtin.service:  
    name: php{{ php_version }}-fpm 
    state: restarted
    enabled: yes
  when: ansible_os_family == 'Debian'

# systemctl restart php-fpm.service
- name: Start php-fpm service RedHat
  ansible.builtin.service:  
    name: php-fpm 
    state: restarted
    enabled: yes
  when: ansible_os_family == 'RedHat'