---
# handlers file for opensearch
- name: reload systemd configuration
  become: true
  ansible.builtin.command: systemctl daemon-reload

# systemctl daemon_reload && systemctl restart opensearch
- name: restart opensearch
  ansible.builtin.systemd: 
    name: opensearch
    state: restarted
    daemon_reload: true

# systemctl daemon_reload && systemctl restart logstash
- name: restart logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    daemon_reload: true