---
- name: Debian OS
  block:

  # apt install nginx -y
  - name: Install nginx Debian
    ansible.builtin.apt:
      name:
        - nginx
      state: latest
      update_cache: yes

  
  - name: Template nginx config files
    ansible.builtin.template:
      src: "nginx/{{ item }}.j2"
      dest: "/etc/nginx/{{ item }}"
    loop:
      #- nginx.conf
      #- conf.d/upstreams.conf
      - sites-available/upstreams

  
  - name: Create a symbolic default link to /etc/nginx/sites-available/upstreams
    ansible.builtin.file:
      src: /etc/nginx/sites-available/upstreams
      dest: /etc/nginx/sites-enabled/default
      state: link

  when: ansible_os_family == "Debian"

- name: Redhat OS
  block:

  # dnf install nginx -y
  - name: Install nginx RedHat
    ansible.builtin.dnf:
      name:
        - nginx
      state: latest

  # cp ./nginx/conf.d/upstreams.conf.j2 /etc/nginx/conf.d/upstreams.conf
  - name: Template nginx config files
    ansible.builtin.template:
      src: "nginx/{{ item }}.j2"
      dest: "/etc/nginx/{{ item }}"
    loop:
      - nginx.conf
      - conf.d/upstreams.conf

  
  when: ansible_os_family == "RedHat"

# systemctl enable nginx --now
- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes