--- 
- name: Debian OS
  block:  

  # apt install
  - name: Installing NFTABLES Debian
    ansible.builtin.apt:
      name: nftables
      state: present


  - name: Copy nftables.conf Debian
    ansible.builtin.template:
      src: nftables/nftables.conf.j2
      dest: /etc/nftables.conf
      owner: root 
      mode: 0600

  when: ansible_os_family == "Debian"

- name: Redhat OS
  block:

  # yum install
  - name: Installing NFTABLES RedHat
    ansible.builtin.dnf:
      name: nftables
      state: present


  - name: Copy nftables.conf RedHat
    ansible.builtin.template:
      src: nftables/nftables.conf.j2
      dest: /etc/sysconfig/nftables.conf
      owner: root 
      mode: 0600


  when: ansible_os_family == "RedHat"

# systemctl restart nftables --now
- name: Restart NFTables 
  ansible.builtin.service:
    name: nfttables 
    state: restarted
    enabled: yes 