---
- name: Include nftables service
  include_tasks: nftables.yml

- name: Include selinux setting
  include_tasks: selinux.yml
  when: ansible_os_family == "RedHat"


- name: Include nginx service
  include_tasks: nginx.yml

- name: Include php-fpm service
  include_tasks: php-fpm.yml