---
# dnf install policycoreutils-python-utils -y
- name: Install policycoreutils-python-utils
  ansible.builtin.dnf:
    name:
      - policycoreutils-python-utils
    state: present


# setsebool -P httpd_can_network_connect_db 1
- name: Set httpd_can_network_connect_db flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true