---
# systemctl restart chronyd
- name: Restart Chronyd RedHat
  ansible.builtin.service:
    name: chronyd
    state: restarted
    daemon_reload: yes 


# systemctl enable php-fpm --now
- name: Start php-fpm service RedHat
  ansible.builtin.systemd:
    name: "php-fpm"
    state: restarted
    enabled: yes
  when: ansible_os_family == "RedHat"

# systemctl restart pcsd
- name: "restart pcsd"
  systemd:
    name: pcsd.service
    state: restarted