---
# systemctl restart chrony
- name: Restart Chrony Debian
  ansible.builtin.service:
    name: chrony
    state: restarted
    daemon_reload: true

# systemctl restart chronyd
- name: Restart Chronyd RedHat
  ansible.builtin.service:
    name: chronyd
    state: restarted
    daemon_reload: true

    