--- 
# systemctl restart chrony
- name: Restart Chrony Debian 
  ansible.builtin.service:
    name: chrony 
    state: restarted 
    demon_reload: yes 

# systemctl restart chronyd
- name: Restart Chronyd RedHat 
  ansible.builtin.service:
    name: chronyd
    state: restarted
    demon_reload: yes   

    