--- 
- name: Debian OS 
  block: 
  
    # apt install keepalived haproxy -y
    - name: Install packages Debian
      ansible.builtin.apt:
        name:
          - keepalived
          - haproxy
        state: latest
        update_cache: true

  when: ansible_os_family == "Debian"

- name: RedHat OS
  block:

    # dnf install keepalived haproxy -y
    - name: Install packages RedHat
      ansible.builtin.yum:
        disable_gpg_check: yes
        name:
          - keepalived
          - haproxy
        state: latest
        update_cache: true


  when: ansible_os_family == "RedHat"