--- 
---
# sudo echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf && \
# sudo sysctl -p /etc/sysctl.conf
- name: Change sysctl config
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop: 
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.ipv4.ip_nonlocal_bind', value: '1' }