# Default values for Chart-mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  #repository: percona/percona-server
  repository: mysql
  tag: "8.0"

service:
  type: ClusterIP
  port: 3306

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
  - name: mysql-db-path
    persistentVolumeClaim:
      claimName: pvc-hdd

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: mysql-db-path
    mountPath: "/var/lib/mysql"