--- 
# cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
- name: Backup default haproxy config file
  ansible.builtin.copy:
    src: /etc/haproxy/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg.backup
    remove_src: true

# copy haproxy/haproxy.cfg.j2 /etc/haproxy/haproxy.cfg
- name: Template custom haproxy config file 
  ansible.builtin.template:
    src: haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg 

# systemctl enable haproxy --now
- name: Start HAProxy Service
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: yes