--- 
# copy keepalived/keepalived.conf.j2 /etc/keepalived/keepalived.conf
- name: Backup default keepalived config file 
  ansible.builtin.copy:
    src: /etc/keepalived/keepalived.conf
    dest: /etc/keepalived/keepalived.conf.backup
    remove_src: true

# copy keepalived/keepalived.conf.j2 /etc/keepalived/keepalived.conf
- name: Template custom keepalived config file 
  ansible.builtin.template:
    src: keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

# systemctl enable keepalived --now
- name: Start Keepalived Service
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: yes