---
- name: Include nftables service
  include_tasks: nftables.yml

- name: Include sysctl config
  include_tasks: sysctl.yml

- name: Include nginx service
  include_tasks: nginx.yml

- name: Include selinux setting
  include_tasks: selinux.yml
  when: ansible_os_family == "RedHat"