--- 
# systemctl enable nftables --now
- name: Start NFTables Service
  ansible.builtin.systemd:
    name: nftables 
    state: started 
    


# systemctl enable nginx --now
- name: Start Nginx Service
  ansible.builtin.systemd:
    state: started
    name: nginx 
   

    