apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: {{ .Release.Name }}
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-svc
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.db.name }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.db.users.user.name }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.db.users.user.password }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag  }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP