- name: Redhat OS
  block:

  # dnf install keepalived haproxy -y
  - name: Install packages RedHat
    ansible.builtin.dnf:
      name:
        - keepalived
        - haproxy
      state: latest
      update_cache: true
  
  when: ansible_os_family == "RedHat"